import time
import random
import requests
from requests.models import HTTPError

url = "http://affiliate.apileads.tech/api/lead-create"

i = 1
while i <= 4:
    i += 1

    langs = [
        'af',
        'am',
        'ar',
        'az',
        'be',
        'bg',
        'bi',
        'bn',
        'bs',
        'ca',
        'ch',
        'cs',
        'da',
        'de',
        'dv',
        'dz',
        'el',
        'en',
        'es',
        'et',
        'fa',
        'fi',
        'fo',
        'fr',
        'he',
        'hi',
        'hr',
        'hu',
        'hy',
        'is',
        'it',
        'ja',
        'ka',
        'kk',
        'kl',
        'km',
        'ko',
        'ky',
        'lb',
        'lo',
        'lt',
        'lv',
        'mg',
        'mi',
        'mk',
        'mn',
        'mt',
        'my',
        'na',
        'nb',
        'ne',
        'nl',
        'no',
        'pl',
        'pt',
        'ro',
        'ru',
        'rw',
        'si',
        'sk',
        'sl',
        'sm',
        'so',
        'sq',
        'sr',
        'sv',
        'sw',
        'tg',
        'th',
        'ti',
        'tk',
        'tr',
        'uk',
        'uz',
        'vi',
        'zh',]

    countrys = [
        'ad',
        'ae',
        'af',
        'ag',
        'al',
        'am',
        'ao',
        'ar',
        'at',
        'au',
        'az',
        'ba',
        'bb',
        'bd',
        'be',
        'bf',
        'bg',
        'bh',
        'bi',
        'bj',
        'bn',
        'bo',
        'br',
        'bs',
        'bt',
        'bw',
        'by',
        'bz',
        'ca',
        'cd',
        'cf',
        'ch',
        'ci',
        'cl',
        'cm',
        'cn',
        'co',
        'cr',
        'cu',
        'cv',
        'cy',
        'cz',
        'de',
        'dj',
        'dk',
        'dm',
        'do',
        'dz',
        'ec',
        'ee',
        'eg',
        'er',
        'es',
        'et',
        'fi',
        'fj',
        'fm',
        'fr',
        'ga',
        'gb',
        'gd',
        'ge',
        'gf',
        'gh',
        'gm',
        'gn',
        'gq',
        'gr',
        'gt',
        'gw',
        'hn',
        'hr',
        'ht',
        'hu',
        'id',
        'ie',
        'il',
        'in',
        'iq',
        'ir',
        'is',
        'it',
        'jm',
        'jo',
        'jp',
        'ke',
        'kg',
        'kh',
        'ki',
        'km',
        'kn',
        'kp',
        'kr',
        'kw',
        'kz',
        'la',
        'lb',
        'lc',
        'li',
        'lk',
        'lr',
        'ls',
        'lt',
        'lu',
        'lv',
        'ly',
        'ma',
        'mc',
        'md',
        'me',
        'mg',
        'mh',
        'mk',
        'ml',
        'mm',
        'mn',
        'mr',
        'mt',
        'mu',
        'mv',
        'mw',
        'mx',
        'my',
        'mz',
        'na',
        'ne',
        'ng',
        'ni',
        'nl',
        'no',
        'np',
        'nr',
        'nz',
        'om',
        'pa',
        'pe',
        'pg',
        'ph',
        'pk',
        'pl',
        'ps',
        'pt',
        'pw',
        'py',
        'qa',
        'ro',
        'rs',
        'ru',
        'rw',
        'sa',
        'sb',
        'sc',
        'sd',
        'se',
        'sg',
        'si',
        'sk',
        'sl',
        'sm',
        'sn',
        'so',
        'sr',
        'ss',
        'st',
        'sv',
        'sy',
        'sz',
        'td',
        'tg',
        'th',
        'tj',
        'tl',
        'tm',
        'tn',
        'to',
        'tr',
        'tt',
        'tv',
        'tz',
        'ua',
        'ug',
        'us',
        'uy',
        'uz',
        'va',
        'vc',
        've',
        'vn',
        'vu',
        'ws',
        'ye',
        'za',
        'zm',
        'zw']

    phoneCode = [
        '396698',
        '67078',
        '21821',
        '6882',
        '6723',
        '6721',
        '5999',
        '1876',
        '1869',
        '1868',
        '1849',
        '1784',
        '1767',
        '1758',
        '1721',
        '1684',
        '1671',
        '1670',
        '1664',
        '1649',
        '1473',
        '1441',
        '1345',
        '1340',
        '1284',
        '1268',
        '1264',
        '1246',
        '1242',
        '998',
        '996',
        '995',
        '994',
        '993',
        '992',
        '977',
        '976',
        '975',
        '974',
        '973',
        '972',
        '971',
        '970',
        '968',
        '967',
        '966',
        '965',
        '964',
        '963',
        '962',
        '961',
        '960',
        '886',
        '880',
        '856',
        '855',
        '853',
        '852',
        '850',
        '692',
        '691',
        '690',
        '689',
        '687',
        '686',
        '685',
        '683',
        '682',
        '681',
        '680',
        '679',
        '678',
        '677',
        '676',
        '675',
        '674',
        '673',
        '628',
        '599',
        '598',
        '597',
        '596',
        '595',
        '594',
        '593',
        '592',
        '591',
        '590',
        '509',
        '507',
        '506',
        '505',
        '504',
        '503',
        '502',
        '501',
        '500',
        '423',
        '421',
        '420',
        '389',
        '387',
        '386',
        '385',
        '382',
        '381',
        '380',
        '378',
        '377',
        '376',
        '375',
        '374',
        '373',
        '372',
        '371',
        '370',
        '359',
        '358',
        '357',
        '356',
        '355',
        '354',
        '353',
        '352',
        '351',
        '350',
        '299',
        '298',
        '297',
        '291',
        '290',
        '269',
        '268',
        '267',
        '266',
        '265',
        '264',
        '263',
        '262',
        '261',
        '260',
        '258',
        '257',
        '256',
        '255',
        '254',
        '253',
        '252',
        '251',
        '250',
        '249',
        '248',
        '247',
        '246',
        '245',
        '244',
        '243',
        '242',
        '241',
        '240',
        '239',
        '238',
        '237',
        '236',
        '235',
        '234',
        '233',
        '232',
        '231',
        '230',
        '229',
        '228',
        '227',
        '226',
        '225',
        '224',
        '223',
        '222',
        '221',
        '220',
        '216',
        '213',
        '212',
        '211',
        '98',
        '95',
        '94',
        '93',
        '92',
        '91',
        '90',
        '86',
        '84',
        '82',
        '81',
        '77',
        '66',
        '65',
        '64',
        '63',
        '61',
        '60',
        '58',
        '57',
        '56',
        '55',
        '54',
        '53',
        '52',
        '51',
        '49',
        '48',
        '47',
        '46',
        '45',
        '44',
        '43',
        '41',
        '40',
        '39',
        '36',
        '34',
        '32',
        '31',
        '30',
        '27',
        '20',
        '7',
        '1', ]

    a = ['test1', 'test2', 'test3', 'test4', 'test5', 'test6', 'test7', 'test8', 'test9', 'test10', 'test11', 'test12']

    b = ['loan', 'general', 'loan', 'general', 'loan', 'general', 'loan', 'general', 'loan', 'general', 'loan', 'general']

    c = ['Mozilla/5.0 (Windows NT 6.3; WOW64)', 'AppleWebKit/537.36 (KHTML, like Gecko)', 'Chrome/94.0.4606.71 Safari/537.36']

    ip = ".".join(map(str, (random.randint(0, 255) for _ in range(4))))

    payload = { 
        'phone': '9' + (str(random.randint(1, 999999999))),
        'phone_code': random.choice(phoneCode),
        'email': 'test' + (str(random.randint(10000, 99999))) + '@test.3snet.tech',
        'firstname': 'TestFirstName' + (str(random.randint(100, 999))),
        'lastname': 'TestLastName' + (str(random.randint(100, 999))),
        'type': random.choice(b),
        'amount': random.choice(a),
        'lang': random.choice(langs),
        'user_agent': random.choice(c),
        'country': random.choice(countrys),
        'ip': ip }

    headers = {'key': 'md6b9h2qXiOhBlOVHQmYYvyWbzbo8k9O'}

    response = requests.request("POST", url, headers=headers, data=payload)
    
    if (response.status_code <= 299):
        print(payload)
        print("Status Code:", response.status_code)
        print(response.text)
    else:
        print("Status Code not 200! Error! Status Code:", response.status_code)

    try:
        assert response.status_code == 200
        assert response.status_code != 403
        assert response.status_code != 404
    except (BaseException, HTTPError):
        print("Status Code not 200! Error! Status Code:", response.status_code)

    time.sleep(5)


